### ISSUE TITLE
dnlib.DotNet.Writer.ModuleWriterException when merging IL of two methods with if statements

### ISSUE THREAD

**Issue by bramhaag** [0xd4d/dnlib#150]
I'm merging two methods and save it to an assembly. For the details, see [this SO post](https://stackoverflow.com/questions/48042418/dnlib-dotnet-writer-modulewriterexception-when-merging-il-of-two-methods)

Since the IL is completely valid, this might be a library bug.

**Comment by bramhaag** [comment]
In my case, the fix to comment out the `Error` line in `MethodBodyWriterBase#GetOffset(Instruction)` and instead of returning 0, returning the `Offset` of the instruction. However, this feels rather like a hack which will only work for my situation and probably not for others, so I won't PR this fix.

**Comment by 0xd4d** [comment]
The exception's message is sometimes useful. You've probably moved an instruction from some method A to some other method B and that instruction still references another instruction in method A, now that it's in method B.

**Comment by bramhaag** [comment]
@0xd4d I do not think so. I printed the IL instructions to the console before calling the Write function, this is what I got:
```
IL_0000: ldstr "Hello"
IL_0005: call System.String System.String::Trim()
IL_000A: ldstr "Hello"
IL_000F: call System.Boolean System.String::op_Equality(System.String,System.String)
IL_0014: brfalse.s IL_0020
IL_0016: ldstr "Hello"
IL_001B: call System.Void System.Console::WriteLine(System.String)
IL_0020: ldsfld System.String GameManager::m_GameVersionString
IL_0025: stloc.0
IL_0026: ldsfld System.String GameManager::m_Changelist
IL_002B: ldsfld System.String System.String::Empty
IL_0030: call System.Boolean System.String::op_Inequality(System.String,System.String)
IL_0035: brfalse.s IL_004D
IL_0037: ldloc.0
IL_0038: ldstr " ("
IL_003D: ldsfld System.String GameManager::m_Changelist
IL_0042: ldstr ")"
IL_0047: call System.String System.String::Concat(System.String,System.String,System.String,System.String)
IL_004C: stloc.0
IL_004D: ldloc.0
IL_004E: ldstr " Release "
IL_0053: call System.String System.String::Concat(System.String,System.String)
IL_0058: stloc.0
IL_0059: ldloc.0
IL_005A: ret
```

[This](https://owo.whats-th.is/a0783e.png) is what the (valid) IL I generated with dnSpy looks like. I cannot find any differences between them.

**Comment by 0xd4d** [comment]
Two twins also look alike, but they're different. :)

You get that message because it couldn't find the instruction in the body. Prove to me that that instance actually exists in the body then I'll have a closer look. I've seen this too many times before.

**Comment by bramhaag** [comment]
I used the following code to test:
```csharp
private static void CheckInstructions(MethodDef method)
{
    
    var instructions = method.Body.Instructions;
    
    foreach (var instruction in instructions)
    {
        Console.WriteLine(instruction);
    }

    var result = instructions
        .Where(i => i.IsConditionalBranch())
        .Select(i => HasInstruction(instructions, i.Offset))
        .All(b => b);

    Console.WriteLine("Result is: " + result);
}

private static bool HasInstruction(IEnumerable<Instruction> instructions, uint offset)
{
    return instructions
        .Select(i => i.Offset)
        .FirstOrDefault(o => o == offset) != default(uint);
}
```

The full console output is:
```
IL_0000: ldc.i4.0
IL_0001: ldc.i4.s 10
IL_0003: add
IL_0004: ldc.i4.s 10
IL_0006: bne.un.s IL_0012
IL_0008: ldstr "i is 10"
IL_000D: call System.Void System.Console::WriteLine(System.String)
IL_0012: ldstr "Hello"
IL_0017: ldstr ", World"
IL_001C: call System.String System.String::Trim()
IL_0021: call System.String System.String::Concat(System.String,System.String)
IL_0026: call System.Void System.Console::WriteLine(System.String)
IL_002B: ldsfld System.String GameManager::m_GameVersionString
IL_0030: stloc.0
IL_0031: ldsfld System.String GameManager::m_Changelist
IL_0036: ldsfld System.String System.String::Empty
IL_003B: call System.Boolean System.String::op_Inequality(System.String,System.String)
IL_0040: brfalse.s IL_0058
IL_0042: ldloc.0
IL_0043: ldstr " ("
IL_0048: ldsfld System.String GameManager::m_Changelist
IL_004D: ldstr ")"
IL_0052: call System.String System.String::Concat(System.String,System.String,System.String,System.String)
IL_0057: stloc.0
IL_0058: ldloc.0
IL_0059: ldstr " Release "
IL_005E: call System.String System.String::Concat(System.String,System.String)
IL_0063: stloc.0
IL_0064: ldloc.0
IL_0065: ret
Result is: True

Unhandled Exception: dnlib.DotNet.Writer.ModuleWriterException: Found some other method's instruction or a removed instruction. You probably removed an instruction that is the target of a branch instruction or an instruction that's the first/last inst
ruction in an exception handler.
   at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\ILogger.cs:line 456
   at dnlib.DotNet.Writer.ModuleWriterBase.dnlib.DotNet.ILogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\ModuleWriterBase.cs:line 1032
   at dnlib.DotNet.Writer.MetaData.Error(String message, Object[] args) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MetaData.cs:line 1274
   at dnlib.DotNet.Writer.MetaData.dnlib.DotNet.Writer.IWriterError.Error(String message) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MetaData.cs:line 3323
   at dnlib.DotNet.Writer.MethodBodyWriter.ErrorImpl(String message) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriter.cs:line 298
   at dnlib.DotNet.Writer.MethodBodyWriterBase.Error(String message) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriterBase.cs:line 56
   at dnlib.DotNet.Writer.MethodBodyWriterBase.GetOffset(Instruction instr) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriterBase.cs:line 96
   at dnlib.DotNet.Writer.MethodBodyWriterBase.WriteShortInlineBrTarget(BinaryWriter writer, Instruction instr) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriterBase.cs:line 369
   at dnlib.DotNet.Writer.MethodBodyWriterBase.WriteOperand(BinaryWriter writer, Instruction instr) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriterBase.cs:line 204
   at dnlib.DotNet.Writer.MethodBodyWriterBase.WriteInstruction(BinaryWriter writer, Instruction instr) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriterBase.cs:line 157
   at dnlib.DotNet.Writer.MethodBodyWriterBase.WriteInstructions(BinaryWriter writer) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriterBase.cs:line 135
   at dnlib.DotNet.Writer.MethodBodyWriter.WriteFatHeader() in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriter.cs:line 160
   at dnlib.DotNet.Writer.MethodBodyWriter.Write() in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MethodBodyWriter.cs:line 113
   at dnlib.DotNet.Writer.MetaData.WriteMethodBodies() in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MetaData.cs:line 1777
   at dnlib.DotNet.Writer.MetaData.Create() in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MetaData.cs:line 1374
   at dnlib.DotNet.Writer.MetaData.CreateTables() in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\MetaData.cs:line 1305
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl() in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\ModuleWriter.cs:line 170
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\ModuleWriterBase.cs:line 519
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\Writer\ModuleWriterBase.cs:line 486
   at dnlib.DotNet.ModuleDef.Write(String filename, ModuleWriterOptions options) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\ModuleDef.cs:line 1163
   at dnlib.DotNet.ModuleDef.Write(String filename) in C:\Users\Bram\Desktop\dnlib-master\src\DotNet\ModuleDef.cs:line 1153
```
Below the IL code it says "Result is: True", meaning all instructions that are referred to are found.

**Comment by 0xd4d** [comment]
No, it doesn't prove it, you're comparing offsets, not instances `Prove to me that that instance actually exists in the body`. You have the source code to dnlib, you know where the exception is thrown, that method has the missing instruction.

**Comment by 0xd4d** [comment]
Some hint: the operand could contain a reference to one or more other instructions in the same body. The offset field is only there for debugging reasons and isn't used when writing the body to the PE file.

**Comment by bramhaag** [comment]
That's weird, because the offset field does solve the issue for me. I changed the [MethodBodyWriterBase#GetOffset](https://github.com/0xd4d/dnlib/blob/master/src/DotNet/Writer/MethodBodyWriterBase.cs#L88) method to:
```csharp
protected uint GetOffset(Instruction instr) {
	if (instr == null) {
		Error("Instruction is null");
		return 0;
	}
	uint offset;
	if (offsets.TryGetValue(instr, out offset))
		return offset;

	Console.WriteLine("Faulty instruction: " + instr);
	//Error("Found some other method's instruction or a removed instruction. You probably removed an instruction that is the target of a branch instruction or an instruction that's the first/last instruction in an exception handler.");
	return instr.Offset; 
}```
and it generated the correct code.

I am unsure how I can prove that "the instance actually exists in the body", but I did find that the faulty instruction (according to the vanilla GetOffSet method) is `IL_0012: ldstr "Hello"`

**Comment by 0xd4d** [comment]
See the code, it adds all instructions to a dictionary. That dictionary is used to look up the instruction that is passed to the method. If the dictionary lookup fails, it means one of 3 things: 1) dictionary is buggy, send a bug report to MS. 2) the dictionary wasn't initialized and is empty, 3) the instruction passed to the method doesn't exist in the body.
