### ISSUE TITLE
Unhandled ModuleWriterException when using ModuleDef.Write()

### ISSUE THREAD

**Issue by binarysnake** [0xd4d/dnlib#270]
I'm getting an exception when using the Write(path); function with a module.
Exception: 
`Unhandled Exception: dnlib.DotNet.Writer.ModuleWriterException: Exception handler: TryEnd <= TryStart`

   `at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.Metadata.dnlib.DotNet.Writer.IWriterError.Error(String message)
   at dnlib.DotNet.Writer.MethodBodyWriter.WriteFatExceptionClauses()
   at dnlib.DotNet.Writer.MethodBodyWriter.WriteExceptionHandlers()
   at dnlib.DotNet.Writer.MethodBodyWriter.Write()
   at dnlib.DotNet.Writer.Metadata.WriteMethodBodies()
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)`

   `at Obfuscator.Program.Main(String[] args) in C:\dev\Obfuscator\Obfuscator\Program.cs:line 129`

Line 129: `module.Write(filePath + "-obfuscated.exe");`

**Comment by 0xd4d** [comment]
You probably moved an instruction that's either the 1st instruction in an exception handler or the first instruction after it.

**Comment by 0xd4d** [comment]
I assume this is fixed.
