### ISSUE TITLE
How to resolve reference with strange characters

### ISSUE THREAD

**Issue by ewwink** [0xd4d/dnlib#283]
if the assembly Reference name like below it throw an error, how to handle this?

```
³ \u0098Ï\u0080H³O\u0010Þ\u0082\u0012º^:\u0018â`Ì3cÈ?Ñ\u0080Èc}pæ\u0098+¦\u0091h§\\ùºg\u0092(¤*D(ÛòÅü?.....
```

```C#
var asmResolver = new AssemblyResolver();
var asmRefs = module.GetAssemblyRefs().ToList();

foreach (var asmRef in asmRefs)
{
    var asma = asmResolver.Resolve(asmRef.FullName, module);
    ((AssemblyResolver)module.Context.AssemblyResolver).AddToCache(asma);
}
```

**Comment by 0xd4d** [comment]
What's the error?

**Comment by ewwink** [comment]
the file is packed with confuser and the error

```
System.ArgumentException
  HResult=0x80070057
  Message=Illegal characters in path.
  Source=mscorlib

```

StackTrace:

```
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at dnlib.DotNet.AssemblyResolver.<FindAssembliesModuleSearchPaths>d__65.MoveNext() in C:\projects\dnlib\src\DotNet\AssemblyResolver.cs:line 657
   at dnlib.DotNet.AssemblyResolver.<FindAssemblies>d__56.MoveNext() in C:\projects\dnlib\src\DotNet\AssemblyResolver.cs:line 545
   at dnlib.DotNet.AssemblyResolver.FindExactAssembly(IAssembly assembly, IEnumerable`1 paths, ModuleContext moduleContext) in C:\projects\dnlib\src\DotNet\AssemblyResolver.cs:line 409
   at dnlib.DotNet.AssemblyResolver.Resolve2(IAssembly assembly, ModuleDef sourceModule) in C:\projects\dnlib\src\DotNet\AssemblyResolver.cs:line 381
   at dnlib.DotNet.AssemblyResolver.Resolve(IAssembly assembly, ModuleDef sourceModule) in C:\projects\dnlib\src\DotNet\AssemblyResolver.cs:line 222
   at dnlib.DotNet.Extensions.Resolve(IAssemblyResolver self, String asmFullName, ModuleDef sourceModule) in C:\projects\dnlib\src\DotNet\IAssemblyResolver.cs:line 46
```

![dnlib-error](https://user-images.githubusercontent.com/760764/60844650-31c3df80-a204-11e9-88d1-9a761f95f17e.jpg)

**Comment by 0xd4d** [comment]
Fixed in master.

If you use the nuget package:

- Compile the code yourself, or
- Catch `ArgumentException`, or
- Don't call `Resolve` if the assembly name contains invalid chars.

**Comment by ewwink** [comment]
Thank you.
