### ISSUE TITLE
How to write P/invoked methods from one assembly to another?

### ISSUE THREAD

**Issue by NotoriousRebel** [0xd4d/dnlib#373]
This is an awesome project and I am trying to get the hang out of it, sadly there are not too many blog posts about it and StackOverflow is a tad scarce :(.
I have two .NET assemblies: A & B.

In B I have P/invoked messagebox from user32.dll as such:
```csharp

        [DllImport("user32.dll")]
        public static extern int MessageBoxA(
           IntPtr hWnd,
           String text,
           String caption,
           int options);
```
And I call it inside main method of B as such:
```MessageBoxA(IntPtr.Zero, "hello from B ssembly", "from messagebox", 1);```

I have been struggling for a few hours to try and figure out how to write the P/invoked messagebox from B to the body of assembly A. When I loop through the methods and get to the P/invoked method the methodbody is null and there are no instructions, but I see it getting called just fine in the entrypoint's body instructions. Any help would be appreciated :D, would I need to worry about imports as well if assembly A didn't import the System.Runtime.InteropServices namespace?

**Comment by 0xd4d** [comment]
Problems like this can usually be solved by checking how the compiler does it. Did you compile the code and check what the compiler generated?

See https://github.com/0xd4d/dnlib/issues/359

**Comment by NotoriousRebel** [comment]
Thanks for the quick reply :)
I tried to compile the code to inspect it; however, ran into an error: 

```
An exception has occurred while blending: dnlib.DotNet.Writer.ModuleWriterException: Method System.Int32 MoreComplexAssembly.Program::MessageBoxA(System.IntPtr,System.String,System.String,System.Int32) (06000001) is not defined in this module (MCU.exe). A method was removed that is still referenced by this module.
   at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.ModuleWriterBase.dnlib.DotNet.ILogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.NormalMetadata.GetRid(MethodDef md)
   at dnlib.DotNet.Writer.Metadata.AddMDTokenProvider(IMDTokenProvider tp)
   at dnlib.DotNet.Writer.Metadata.GetToken(Object o)
   at dnlib.DotNet.Writer.MethodBodyWriter.WriteInlineMethod(ArrayWriter& writer, Instruction instr)
   at dnlib.DotNet.Writer.MethodBodyWriterBase.WriteOperand(ArrayWriter& writer, Instruction instr)
   at dnlib.DotNet.Writer.MethodBodyWriterBase.WriteInstruction(ArrayWriter& writer, Instruction instr)
   at dnlib.DotNet.Writer.MethodBodyWriterBase.WriteInstructions(ArrayWriter& writer)
   at dnlib.DotNet.Writer.MethodBodyWriter.WriteFatHeader()
   at dnlib.DotNet.Writer.MethodBodyWriter.Write()
   at dnlib.DotNet.Writer.Metadata.WriteMethodBodies()
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.Metadata.CreateTables()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.ModuleDef.Write(Stream dest)

```
Here is a code snippet of what I am doing (there are a fair amount of comments as I have tried a bit 

```csharp
     /*
                                                int firstInstrutCnt = firstentryPoint.Body.Instructions.Count;
                                                int secondInstructCnt = secondentryPoint.Body.Instructions.Count;
                                                Instruction nop = new Instruction(OpCodes.Nop);

                                                int iterator = secondentryPoint.Body.Instructions[secondInstructCnt - 1].OpCode == OpCodes.Ret ? secondInstructCnt - 1 : secondInstructCnt;
                                                // Check if last instruction is a ret and do not insert that instruction as that would disturb flow of benign assembly
                                                
                                                for (int i = 0; i < iterator; i++)
                                                {
                                                    Console.WriteLine($"inserting second instruction at index: {i} with instruction: {secondentryPoint.Body.Instructions[i]}", Color.MintCream);
                                                    //firstentryPoint.Body.Instructions[i] = secondentryPoint.Body.Instructions[i];
                                                    firstentryPoint.Body.Instructions.Insert(i, secondentryPoint.Body.Instructions[i]);
                                                    //firstentryPoint.Body.Instructions.Add(dnlib.DotNet.Emit.OpCodes.Call.ToInstruction(method.Module.Import(GetSystemMethod(typeof(MessageBox), "Show", new Type[] { typeof(string) }))));
                                                    //secondentryPoint.Body.Instructions.Insert(i, firstentryPoint.Body.Instructions[i]);
                                                }
                                               
                                                Console.WriteLine($"Writing blended assembly to: {outputPath}", Color.Plum);
                                                */
                                                var types = secondModule.GetTypes();
                                                //var methods = types.GetEnumerator().MoveNext().MEthods
                                                Instruction ret = new Instruction(OpCodes.Ret);
                                                foreach(var type in types)
                                                {
                                                    Console.WriteLine($"Looping through methods!");
                                                    //if (type.Name.Contains(secondModule.Name))
                                                    //{
                                                       foreach(var method in type.Methods)
                                                        {
                                                        /*
                                                            if (method.IsPinvokeImpl)
                                                            {
                                                            // We can't add the pinvoked method to entrypoint as that will break things instead 
                                                            // We shall add it to the module body
                                                            //var body = method.Body.Instructions;
                                                            //Console.WriteLine(body);
                                                            //Importer import = new Importer(secondModule);
                                                            //TypeDef mexxthod = method.DeclaringType;
                                                            //IMethod test = import.Import(typeof(mexxthod))
                                                           // IMethod wow = import.Import(typeof(void))
                                                            Console.WriteLine($"{method.Name} is pinvoked method have to add manually for now...");
                                                            }
                                                            else 
                                                            { */
                                                                Console.WriteLine($"Does {method.Name} have a body?", Color.Aqua);
                                                                if (method.HasBody && method.Name.Contains("Main") || method.Name.Contains("main"))
                                                                {
                                                                    if (method.Attributes.HasFlag(dnlib.DotNet.MethodAttributes.Static))
                                                                    {
                                                                        Console.WriteLine($"{method.Name} was static changing now!");
                                                                        method.Attributes ^= dnlib.DotNet.MethodAttributes.Private;
                                                                        method.Attributes |= dnlib.DotNet.MethodAttributes.Public;
                                                                        method.Attributes &= ~dnlib.DotNet.MethodAttributes.Static;
                                                                    }
                                                                    method.Attributes |= dnlib.DotNet.MethodAttributes.Public;

                                                                    Console.WriteLine("Method has a body!", Color.White);
                                                                    for (int i = 0; i < method.Body.Instructions.Count - 1; i++)
                                                                    {
                                                                        if (method.Body.Instructions[i] != ret)
                                                                        {
                                                                            // If instruction is a ret skip it as to not break method!
                                                                            Console.WriteLine($"Inserting: {method.Body.Instructions[i]}");
                                                                            firstentryPoint.Body.Instructions.Insert(i, method.Body.Instructions[i]);
                                                                        }
                                                                        else
                                                                        {
                                                                            Console.WriteLine($"Skipping ret instruction", Color.Red);
                                                                        }

                                                                    }
                                                                    //firstentryPoint.Body.Instructions.Add(OpCodes.Call.ToInstruction(method));
                                                                    //firstentryPoint.Body.Instructions.Add(OpCodes.Newobj.ToInstruction(method));
                                                                    //firstModule.
                                                                    //method.Att

                                                                    var yy = OpCodes.Newobj.ToInstruction(method);

                                                                    Console.WriteLine(yy);
                                                                    //firstentryPoint.Body.Instructions.Add(OpCodes.Newobj.ToInstruction(method));
                                                                    //firstentryPoint.Body.Instructions.Add(OpCodes.Call.ToInstruction(method));
                                                                //}
                                                        }

                                                        // }
                                                    }
                                                }

                                                var stream = File.Create(outputPath);
                                                firstModule.Write(stream);
                                                stream.Close();


```

**Comment by 0xd4d** [comment]
It says MessageBoxA isn't part of a type's Methods list. Did you add it to the Methods list?

**Comment by NotoriousRebel** [comment]
I am not sure the best way to do that I see the method I can see the implmap and maybe then use Importer class with ImportMapper? I do not wish to create a new module.
Just basing that off of this StackOverflow [post](https://stackoverflow.com/questions/54441057/inject-a-class-with-a-method-using-dnlib)
![image](https://user-images.githubusercontent.com/36310667/85952035-b7203280-b934-11ea-8f5d-fb6b8ddd73b2.png)

**Comment by 0xd4d** [comment]
You must add the method to some type's Methods list. `someType.Methods.Add(theMethod)`

**Comment by NotoriousRebel** [comment]
I think I am getting closer?
Getting this error:
```
An excpetion has occurred attempting to add method: Main with: System.InvalidOperationException: Method is already owned by another type. Set DeclaringType to null first.
   at dnlib.DotNet.TypeDef.dnlib.Utils.IListListener<dnlib.DotNet.MethodDef>.OnAdd(Int32 index, MethodDef value)
   at dnlib.Utils.LazyList`1.Add_NoLock(TValue item)
   at dnlib.Utils.LazyList`1.Add(TValue item)
```
```csharp
   var modType = firstModule.GetTypes();
                                                bool x = true;
                                                //modType.Cast<User>().ToList();
                                                //var x = modType[0];
                                                //var firstType = modType.Current;
                                                //var firstType = modType.
                                                var types = secondModule.GetTypes();
                                                //var methods = types.GetEnumerator().MoveNext().MEthods
                                                Instruction ret = new Instruction(OpCodes.Ret);

                                                foreach (var firstType in modType)
                                                {
                                                    if(firstType.FullName.Contains("<Module>"))
                                                    { 
                                                        Console.WriteLine($"Trying to add with type: {firstType.FullName}");
                                                        foreach (var type in types)
                                                        {
                                                            Console.WriteLine($"Looping through methods!");
                                                            //if (type.Name.Contains(secondModule.Name))
                                                            //{
                                                            foreach (var method in type.Methods)
                                                            {
                                                                Console.WriteLine($"Does {method.Name} have a body?", Color.Aqua);
                                                                try
                                                                {
                                                                    firstType.Methods.Add(method);
                                                                }
                                                                catch (Exception e)
                                                                {
                                                                    Console.WriteLine($"An excpetion has occurred attempting to add method: {method.Name} with: {e}", Color.Red);
                                                                    continue;
                                                                }

                                                            }
                                                        }
                                                    }
                                                 }
```

**Comment by 0xd4d** [comment]
The exception message has the solution:

> An excpetion has occurred attempting to add method: Main with: System.InvalidOperationException: Method is already owned by another type. Set DeclaringType to null first.

**Comment by NotoriousRebel** [comment]
I do that and run into another error 😓 
```
An exception has occurred: System.InvalidOperationException: List was modified
   at dnlib.Utils.LazyList`1.Enumerator.MoveNextDoneOrThrow_NoLock()
   at dnlib.Utils.LazyList`1.Enumerator.MoveNext()
```

```csharp
 var modType = firstModule.GetTypes();
bool x = true;
var types = secondModule.GetTypes();
Instruction ret = new Instruction(OpCodes.Ret);

foreach (var firstType in modType)
{
	if(firstType.FullName.Contains("<Module>"))
	{ 
		Console.WriteLine($"Trying to add with type: {firstType.FullName}");
		foreach (var type in types)
		{
			Console.WriteLine($"Looping through methods!");
			//if (type.Name.Contains(secondModule.Name))
			//{
			foreach (var method in type.Methods)
			{
				Console.WriteLine($"Does {method.Name} have a body?", Color.Aqua);
				try
				{
					method.DeclaringType = null;
					firstType.Methods.Add(method);
				}
				catch (Exception e)
				{
					Console.WriteLine($"An excpetion has occurred attempting to add method: {method.Name} with: {e}", Color.Red);
					continue;
				}

			}

		}
	}
 }
```

**Comment by 0xd4d** [comment]
You're modifying a list inside of a for each loop that uses that list. Simple fix: call ToArray() on that list.

**Comment by NotoriousRebel** [comment]
Thank you for all the help fixed it :)
