### ISSUE TITLE
Easiest way to add classes and structs?

### ISSUE THREAD

**Issue by NotoriousRebel** [0xd4d/dnlib#379]
Thank you for the help on the last issue I created I am much closer to having my program work properly; however, I ran into another roadblock. Let's say I have an assembly with two classes and class1 references a struct or class created inside class2. If I am writing the method instructions into a new assembly from the entrypoint's body how can I account for classes and structs as well. I was looking at this [issue](https://github.com/0xd4d/dnlib/issues/104) and it seems a bit helpful, would it be easier to use Confuserex's [injecthelper](https://github.com/yck1509/ConfuserEx/blob/3c9c29d9daf2f1259edf69054c5693d5d225a980/Confuser.Core/Helpers/InjectHelper.cs)

Traceback:
````
An exception has occurred while blending: dnlib.DotNet.Writer.ModuleWriterException: TypeDef Assembly.Class/OBJECT_ATTRIBUTES (0200000C) is not defined in this module (target.exe). A type was removed that is still referenced by this module.
   at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.ModuleWriterBase.dnlib.DotNet.ILogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.NormalMetadata.GetRid(TypeDef td)
   at dnlib.DotNet.Writer.Metadata.AddMDTokenProvider(IMDTokenProvider tp)
   at dnlib.DotNet.Writer.Metadata.AddTypeDefOrRef(ITypeDefOrRef tdr)
   at dnlib.DotNet.Writer.Metadata.dnlib.DotNet.Writer.ISignatureWriterHelper.ToEncodedToken(ITypeDefOrRef typeDefOrRef)
   at dnlib.DotNet.Writer.SignatureWriter.Write(ITypeDefOrRef tdr)
   at dnlib.DotNet.Writer.SignatureWriter.Write(TypeSig typeSig)
   at dnlib.DotNet.Writer.SignatureWriter.Write(TypeSig typeSig)
   at dnlib.DotNet.Writer.SignatureWriter.Write(MethodBaseSig sig)
   at dnlib.DotNet.Writer.SignatureWriter.Write(CallingConventionSig sig)
   at dnlib.DotNet.Writer.SignatureWriter.Write(ISignatureWriterHelper helper, CallingConventionSig sig, DataWriterContext context)
   at dnlib.DotNet.Writer.Metadata.GetSignature(CallingConventionSig sig)
   at dnlib.DotNet.Writer.Metadata.InitializeTypeDefsAndMemberDefs()
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.Metadata.CreateTables()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.ModuleDef.Write(Stream dest)
```
Thank you for all the hard work you put into this project, keep up the great work!

**Comment by 0xd4d** [comment]
Have a look at the `Importer` struct to get a ref to another assembly's def. `ModuleDef.Import()` can be used too.

**Comment by NotoriousRebel** [comment]
Thank you for the suggestion, this was my first stab at it I am still getting the same error; however, I think I am closer:

```csharp
         Importer import = new Importer(firstModule, ImporterOptions.TryToUseDefs);
          foreach(var type in secondModule.GetTypes().ToArray())
           {
                   Console.WriteLine($"Your type is: {type.FullName}");
                    try
                    {
                                 //firstModule.Import(type);
                                   import.Import(type);
                    }
                    catch (Exception e)
                    {
                              Console.WriteLine($"An exception has occurred  {e}");
                     }
             }   
                                                                              
```

**Comment by 0xd4d** [comment]
You need to use the return value of Import() somewhere too, eg. if you have a reference in the IL code or in some type, you should replace all those definitions with the type reference.

**Comment by NotoriousRebel** [comment]
I'm not sure I'm following, let's say I have a struct in assembly A that is not defined in assembly B I want to inject that struct into assembly B. What is the easiest way to do that, should I do what confuserex does and use a helper injector class?

```csharp
Importer import = new Importer(firstModule, ImporterOptions.TryToUseDefs); 
foreach(var type in secondModule.GetTypes().ToArray())
{
	Console.WriteLine($"Your type is: {type.FullName}");
	try
	{
	ITypeDefOrRef result = import.Import(type);
	if(result != null)
	{
		Console.WriteLine($"Obtained reuslt: {result.FullName}");
		firstModule.Types.Add(result.ResolveTypeDef());
	}
	}
	catch (Exception e)
	{
		Console.WriteLine($"An exception has occurred while attempting to import type: {type.Name} : {e}");
	}
}
```
This is leading to an exception:
```
Your type is: ClassA.SubClassinClassA/STRUCT_DATA
Obtained reuslt: ClassA.SubClassinClassA/STRUCT_DATA
An exception has occurred while attempting to import type: STRUCT_DATA: System.NullReferenceException: Object reference not set to an instance of an object.
   at dnlib.DotNet.ModuleDef.dnlib.Utils.IListListener<dnlib.DotNet.TypeDef>.OnAdd(Int32 index, TypeDef value)
   at dnlib.Utils.LazyList`1.Add_NoLock(TValue item)
   at dnlib.Utils.LazyList`1.Add(TValue item)
   at Program(String firstasmpath, String secondasmpath, String outputPath) in
  C:\Program.cs:line 567
```

**Comment by 0xd4d** [comment]
If your assembly A must call Assembly B's method B_M, then you must use a method reference in A to access B_M in assembly B. So when you add your CALL instruction in assembly A, you must set the Operand field to the method reference. You can get this method reference by using the importer if you pass in B's M method to the Import() method.

Something like

```C#
var B_M = find method M in assembly B;
var importer = new Importer(assembly_A.ManifestModule);
var B_M_ref = importer.Import(B_M);
...
var body = some method body in assembly A;
body.Instructions.Add(OpCodes.Call.ToInstruction(B_M_ref));
...
```

**Comment by NotoriousRebel** [comment]
Sorry for the late reply, work was very busy. The one thing I have figured out is methods it's in regards to things such as custom delegates, structs, enums, and other types I am having a hard time with

This is how I am handling methods:

```csharp
var modType = firstModule.GetTypes();

foreach (var firstType in modType)
{
	if(firstType.FullName.Contains("Program"))
	{ 
		Console.WriteLine($"Trying to add with type: {firstType.FullName}");
		foreach (var type in types)
		{	
			IList<MethodDef> methods = type.Methods;
			var test = Enumerable.Range(0, methods.Count).Select(i => methods[i]).ToArray();
			foreach (var method in test)
			{
				Console.WriteLine($"Adding {method.Name} to firstModule");
				try
				{
					if (method.DeclaringType != null)
					{
						method.DeclaringType = null;
					}					
					if (!(method.Name.Equals(secondEntryPointName)))
					{
						if (firstType.Methods.ToList().Contains(method) == false)
						{
							firstType.Methods.Add(method);
						}
					}
				}
				catch (Exception e)
				{
					Console.WriteLine($"An excpetion has occurred attempting to add method: {method.Name} with: {e}");
					continue;
				}

			}
		}
	}
 }
```

It seems to do the job for now will obviously have to tweak some aspects of it such as hardcoding the string Program and could perhaps optimize a bit. However, the bigger issue as mentioned previously is when it comes to everything except methods, this is the code I was using and ran into some issues. I essentially want to remove or just move types from the original module to a new module. 

```csharp
Importer import = new Importer(firstModule, ImporterOptions.TryToUseDefs);

foreach(var type in secondModule.GetTypes().ToArray())
{
	
	//if (type.IsDelegate || type.IsClass || type.IsEnum || type.IsInterface || type.IsCustomFormatClass)
	//{
	Console.WriteLine($"Your type is: {type.FullName}");
	try
	{
	//firstModule.ImportAsTypeSig(type);
	//firstModule.Types.Add(type);
	//firstModule.Import(type);
	ITypeDefOrRef result = import.Import(type);
	if(result != null)
	{
		Console.WriteLine($"Obtained reuslt: {result.FullName}");
		firstModule.Types.Add(result.ResolveTypeDef());
	}

	}
	catch (Exception e)
	{
		Console.WriteLine($"An exception has occurred while attempting to import type: {type.Name} : {e}");
	}
	//}
}
```
