### ISSUE TITLE
Failure to resolve non-primitive mscorlib types

### ISSUE THREAD

**Issue by Agrair** [0xd4d/dnlib#394]
I'm currently trying to create a mirror type of any type defined in a module. The mirror type contains all of the original types fields. I need to do this because, unfortunately, the developers of the original type made literally everything static. But I'm stuck now because the assembly resolver is apparently unable to resolve types such as `System.Collections.Generic.Dictionary<TKey, TValue>`? Is that intentional? I tried adding a reference to `originalMod.CorLibTypes.Boolean.Module` which I thought would point to the module for `CoreLib`, but it just points back to `originalMod`. The error given says that `originalMod` doesn't define `System.Collections.Generic.Dictionary<TKey, TValue>`, and therefore cannot be resolved. Here's the code that throws, along with a proper stack trace.
Code: 
```
            // Read all data immediately to mitigate IO management memory costs
            byte[] data = System.IO.File.ReadAllBytes(SharedContext.targetPath);
            ModuleContext modCtx = ModuleDef.CreateModuleContext();
            // Reading pdb is unnecessary and takes up memory
            ModuleCreationOptions opts = new ModuleCreationOptions(modCtx)
            {
                TryToLoadPdbFromDisk = false
            };
            ModuleDefMD originalMod = ModuleDefMD.Load(data, opts);
            var asmResolver = modCtx.AssemblyResolver as AssemblyResolver;
            // Add the original module to the context
            asmResolver.AddToCache(originalMod);

            //// Edit: Does nothing
            asmResolver.AddToCache(new ModuleDefUser(typeof(void).Module));


            // Create a new module
            ModuleDef mod = new ModuleDefUser(moduleName)
            {
                Kind = ModuleKind.Dll
            };
            mod.Context = modCtx;

            // Add the module to an assembly
            new AssemblyDefUser(assemblyName, new Version(1, 0)).Modules.Add(mod);

            // Create the mirror type
            var mirrorType = new TypeDefUser(namespaceStr, $"{typeName}__Mirror",
                mod.CorLibTypes.Object.TypeDefOrRef)
            {
                Attributes = TypeAttributes.Public | TypeAttributes.AutoLayout |
                    TypeAttributes.Class | TypeAttributes.AnsiClass
            };
            // Add the type to the module
            mod.Types.Add(mirrorType);


            // Get the specified type
            var originalType = originalMod.Types.First(x => x.FullName == typeName);

            foreach (var field in originalType.Fields.Where(x => x.IsStatic))
            {
                //// Edit: Right here, dnlib throws, when trying to resolve either a dictionary field or field whose type contains a dictionary
                var newField = new FieldDefUser(field.Name,
                    new FieldSig(field.FieldType.ToTypeDefOrRef().ResolveTypeDef().ToTypeSig()),
                    FieldAttributes.Static | FieldAttributes.Public);
                mirrorType.Fields.Add(newField);
            }

            mod.Write(outputPath);
```
Log: 
```
dnlib.DotNet.Writer.ModuleWriterException: TypeDef System.Collections.Generic.Dictionary`2 (02000492) is not defined in this module (Terraria). A type was removed that is still referenced by this module.
   at dnlib.DotNet.DummyLogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.ModuleWriterBase.dnlib.DotNet.ILogger.Log(Object sender, LoggerEvent loggerEvent, String format, Object[] args)
   at dnlib.DotNet.Writer.Metadata.Error(String message, Object[] args)
   at dnlib.DotNet.Writer.NormalMetadata.GetRid(TypeDef td)
   at dnlib.DotNet.Writer.Metadata.AddMDTokenProvider(IMDTokenProvider tp)
   at dnlib.DotNet.Writer.Metadata.AddTypeDefOrRef(ITypeDefOrRef tdr)
   at dnlib.DotNet.Writer.Metadata.dnlib.DotNet.Writer.ISignatureWriterHelper.ToEncodedToken(ITypeDefOrRef typeDefOrRef)
   at dnlib.DotNet.Writer.SignatureWriter.Write(ITypeDefOrRef tdr)
   at dnlib.DotNet.Writer.SignatureWriter.Write(TypeSig typeSig)
   at dnlib.DotNet.Writer.SignatureWriter.Write(FieldSig sig)
   at dnlib.DotNet.Writer.SignatureWriter.Write(CallingConventionSig sig)
   at dnlib.DotNet.Writer.SignatureWriter.Write(ISignatureWriterHelper helper, CallingConventionSig sig, DataWriterContext context)
   at dnlib.DotNet.Writer.Metadata.GetSignature(CallingConventionSig sig)
   at dnlib.DotNet.Writer.Metadata.InitializeTypeDefsAndMemberDefs()
   at dnlib.DotNet.Writer.Metadata.Create()
   at dnlib.DotNet.Writer.Metadata.CreateTables()
   at dnlib.DotNet.Writer.ModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)
   at dnlib.DotNet.ModuleDef.Write(String filename, ModuleWriterOptions options)
   at dnlib.DotNet.ModuleDef.Write(String filename)
```
I feel like I'm missing something here. Sorry if I am.

**Comment by 0xd4d** [comment]
The error message says you have a reference to a `TypeDef` in `mod` that's defined in some other module. 

`mod.Import()` can be used to import the field's type into `mod` (it will convert TypeDefs to TypeRefs), eg. `var newField = mod.Import(field);`.

Another thing is that your new module isn't necessarily using the same corlib. You can pass in the original module's CorLib assembly reference to the constructor: `new ModuleDefUser(moduleName, null, originalMod.CorLibTypes.AssemblyRef)`

**Comment by Agrair** [comment]
Sweet, it works! Thanks a bunch for your time!
