### ISSUE TITLE
ModuleWriterException: Invalid section RVA

### ISSUE THREAD

**Issue by Drovosek01** [0xd4d/dnlib#545]
I'm exploring. A dll file compiled using dotNet on a Mac with Apple Silicon processors.

I open the file in [dnSpyEx](https://github.com/dnSpyEx/dnSpy/) v6.5.0 and then just try to save the module without any modifications
<img width="595" alt="Screenshot 2024-02-19 at 16 03 42" src="https://github.com/0xd4d/dnlib/assets/29478700/d1e9f8fe-3006-450b-8643-a48eee5d58d1">
and I get an error:
```
An exception has occurred dnlib.DotNet.Writer.ModuleWriterException: Invalid section RVA
   at dnlib.DotNet.Writer.NativeModuleWriter.WriteFile()
   at dnlib.DotNet.Writer.NativeModuleWriter.Write()
   at dnlib.DotNet.Writer.NativeModuleWriter.WriteImpl()
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(Stream dest)
   at dnlib.DotNet.Writer.ModuleWriterBase.Write(String fileName)
   at dnlib.DotNet.ModuleDefMD.NativeWrite(String filename, NativeModuleWriterOptions options)
   at dnSpy.AsmEditor.SaveModule.ModuleSaver.Save(SaveModuleOptionsVM vm) in D:\a\dnSpy\dnSpy\Extensions\dnSpy.AsmEditor\SaveModule\ModuleSaver.cs:line 187
   at dnSpy.AsmEditor.SaveModule.ModuleSaver.SaveAll() in D:\a\dnSpy\dnSpy\Extensions\dnSpy.AsmEditor\SaveModule\ModuleSaver.cs:line 151
   at dnSpy.AsmEditor.SaveModule.SaveMultiModuleVM.SaveAsync(SaveOptionsVM[] mods) in D:\a\dnSpy\dnSpy\Extensions\dnSpy.AsmEditor\SaveModule\SaveMultiModuleVM.cs:line 250
```
<img width="628" alt="Screenshot 2024-02-19 at 16 04 00" src="https://github.com/0xd4d/dnlib/assets/29478700/5ea147e5-2dfc-4c45-8b0d-a278cdd634f4">

I tried to do this on Windows 10 x64 on an AMD laptop, and also tried to do it on Windows 11 ARM via Parallels Desktop and always get the same error.

Does anyone know how to fix this? Here is an example of such a file: 
[CsvHelper dll for arm64.zip](https://github.com/0xd4d/dnlib/files/14331404/CsvHelper.dll.for.arm64.zip)

**Comment by ElektroKill** [comment]
Probably related to: https://github.com/0xd4d/dnlib/issues/533
